### ISSUE TITLE
navigation to overriding method from Java code takes me to decompiled code

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#397]
If I open a Java method hierarchy on `ChooseByNameContributor.getNames()` or do Navigate > Implementations, and then navigate to `CeylonGotoContributor`, I get taken to the decompiled `.class` file instead of the Ceylon source.

I *suppose* that this is a consequence of #292 or perhaps #334. Can you confirm, @bjansen?

**Comment by bjansen** [comment]
Most likely, yes.

**Comment by gavinking** [comment]
OK, thanks.

**Comment by bjansen** [comment]
I pushed a fix that allows to navigate to source for regular methods like the one in your description, but I need to make more things in #292 to add support for getters/setters etc.

Also, we have the same problem as in #369, i.e. we can't access the model from a `CeylonFile` located in a .src archive unless that file is currently open in an editor, which means "find implementations" currently only works if the file is already open.

**Comment by gavinking** [comment]
@bjansen 👍

**Comment by gavinking** [comment]
Reopening, because it's still not working for the case of *shortcut refinement*. Try with `BreadcrumbsInfoProvider.getElementTooltip()`, navigating to `CeylonBreadcrumbsInfoProvider`.

**Comment by bjansen** [comment]
Please report remaining bugs in #292 instead of reopening this one, they are duplicates anyway.

**Comment by gavinking** [comment]
@bjansen OK, good, much better. The remaining problem case is `languages` refining `getLanguages()`, but I guess we can continue discussion of that case in #292.

**Comment by gavinking** [comment]
Wait, @bjansen, #292 actually has nothing to do with this issue. #292 is specifically about *binary* declarations, where member navigation from Java isn't working *at all*. (Navigation to types *is* working, it seems.)

*This issue* includes (and is most important for) navigation to *project source declarations*, where navigation to implementing members from Java  *does work*, except for the case of getters.

So the issues are not actually related to one another. I'm going to reopen this again, because I don't see any other open issue that would be the right place to report the problem with navigating to Ceylon attributes that implement Java getters.

**Comment by bjansen** [comment]
They *are* the same issue. ceylon-ide-intellij is a Java project that imports `ceylonCode.car`, so it's also binary declarations for which we need to attach sources. 

For Ceylon functions that override Java methods, there is indeed another problem for which we should open another issue though: if you open the Java interface and click on the `I↓` icon in the gutter, it won't even *show* the Ceylon implementations.

**Comment by bjansen** [comment]
To clarify: navigation from Java code to Ceylon code, and navigation done via "find implementations" is exactly the same feature when it comes to Ceylon code in .car archives, which is what #397 and #292 are about.

**Comment by gavinking** [comment]
@bjansen That doesn't make sense. Navigation to Ceylon member declarations for Java code doesn't work _at all_. Here, it only doesn't work in the case of attributes.

**Comment by bjansen** [comment]
Dammit, those titles are such vague that they look like the same issue

**Comment by gavinking** [comment]
I agree the titles suck.

FTR, I think I see the cause of the problem `NavigationPsiClass.wrapMethods()` simply ignores `AnyAttributes`, so doesn't create `NavigationPsiMethod`s for getters and setters.

@bjansen given that, this should be easy to fix.

**Comment by bjansen** [comment]
> "Go to" navigation to Ceylon member declarations from Java code doesn't work at all.

If both Ceylon and Java declarations are in the same project, that's covered by #350.

If a Java project depends on a .car, and Java code calls Ceylon members, this is covered by #292. By default, IntelliJ will open the decompiled class, and we need to attach Ceylon source to that. I already attached classes and simple functions, but I still need to add getters and setters, and perhaps a few other cases I'm forgetting about.

The problems you are having in #397 are the same as #292, it's a Java project that depend on a .car, so by default IntelliJ opens the decompiled stuff, and we just have to attach sources correctly.

**Comment by gavinking** [comment]
@bjansen No. Read my previous comment.

**Comment by bjansen** [comment]
> NavigationPsiClass.wrapMethods() simply ignores AnyAttributes

yes, that's exactly what I have to do to finish #292

**Comment by gavinking** [comment]
Then why does navigation to Ceylon methods from Java code not work?

**Comment by davidfestal** [comment]
This works now for me after my last commit that uses the result of #427.

For example navigating from `AbstractMap.containsKey()` to `JavaMap` through the `go to implementations` brings me the the Ceylon source code of the `JavaMap.containsKey()` method.  

@gavinking @bjansen do you confirm?

**Comment by gavinking** [comment]
No, it's still not working for the thing in the original issue description: `ChooseByNameContributor.getNames()`.

**Comment by bjansen** [comment]
Oops, I might have broken something...

**Comment by davidfestal** [comment]
OK, this was another problem then ?

**Comment by bjansen** [comment]
yes

**Comment by gavinking** [comment]
Yaaay, finally fixed!! :)

**Comment by bjansen** [comment]
🎉
