### ISSUE TITLE
Find Implementations not showing Ceylon functions

### ISSUE THREAD

**Issue by bjansen** [ceylon/ceylon-ide-intellij#418]
I have a Ceylon module that imports the IntelliJ SDK and defines this class:

```ceylon
class Foo() satisfies ChooseByNameContributor {
    shared actual ObjectArray<NavigationItem> getItemsByName(String? s, String? s1, Project? project, Boolean b) => nothing;

    shared actual ObjectArray<JString> getNames(Project? project, Boolean b) => nothing;
}
```

When I open `ChooseByNameContributor` and click on the `I↓` icon on any method, it doesn't show `Foo` in the results.

**Comment by gavinking** [comment]
This is fixed, it seems to me.

**Comment by bjansen** [comment]
Nope, still not working. It works in ceylon-ide-intellij because it's showing the compiled class in `org.intellij.plugins.ceylon.ide.ceylonCode-current.car`, for which sources are attached when we navigate. But in a pure Ceylon project like the one in the description, it doesn't show anything.

The only thing that works is `⌥⌘␣` on `ChooseByNameContributor`, but clicking on `I↓` for the class doesn't show `Foo` in the results.

**Comment by gavinking** [comment]
@bjansen OK, now I see.

**Comment by bjansen** [comment]
Now ⌥⌘B shows Ceylon results for both `PsiClass`es and `PsiMethod`s.

Unfortunately, to be able to show our results when clicking on `I↓`, we'd have to make our own PSI elements satisfy `PsiClass` or `PsiMethod` (the `QueryExecutor`s to implement don't handle generic `PsiElement`s), so I'll leave that for later.
