### ISSUE TITLE
Missing results when trying to autocomplete exceptions

### ISSUE THREAD

**Issue by bjansen** [ceylon/ceylon-ide-intellij#512]
```ceylon
try {
} catch (As<cursor here>) {
}
```

In the above scenario, I don't see `AssertionError`, for example.

It looks like it only shows exceptions from the current package and some of the exceptions in `ceylon.language` when the prefix is empty, and no result at all as soon as there is a prefix.

**Comment by bjansen** [comment]
Actually, the same problem appears in Eclipse. The completion manager is trying to restrict proposals to declarations that match the given condition:

```ceylon
    Boolean isExceptionType(Unit unit, Declaration dec) 
            => if (is TypeDeclaration dec) 
            then dec.inherits(unit.exceptionDeclaration) 
            else false;
```

But here, `AssertionError` (and probably a lot of other exceptions) inherit from `j.l.Exception` or `c.l.Throwable`, so in fact they don't inherit from `c.l.Exception`.

I'm not sure if model loaders should treat all exceptions as children of `c.l.Exception`, or if the function above should check for children of `c.l.Throwable` and `j.l.Throwable` instead.

@davidfestal and @gavinking wdyt?

**Comment by gavinking** [comment]
> the function above should check for children of `c.l.Throwable` and `j.l.Throwable` instead

Of course. Obviously that code was written before we had `Throwable`.

**Comment by gavinking** [comment]
@bjansen should be fixed.

**Comment by bjansen** [comment]
Good thing it was assigned *to me*...

**Comment by bjansen** [comment]
Still not working on non-empty prefixes, probably because in this case we are querying IntelliJ's index.

**Comment by gavinking** [comment]
We probably don't set the supertype in that case.
